platform :ios, '9.0'
use_frameworks!

target 'Handshake' do

pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'PGMappingKit'
pod 'MGSwipeTableCell'
pod 'Persei', '~> 2.0.1'
pod 'UIView+Shake'

end

target 'HandshakeTests' do

end

target 'HandshakeUITests' do

end

